version: '3'
services:
        web:
                build: .
                expose:
                        - "8080"
                environment:
                        - APP_ID="${APP_ID}"  
                        - APP_TOKEN="${APP_TOKEN}"
                command: web -usertoken="${USER_TOKEN}"
                depends_on:
                        - db

        nginx:
                build: ./nginx/
                ports:
                        - "80:80"
                links:
                        - web:web

        db:
                build: ./postgresql/
